function(add_vox_model PATH)
    get_filename_component(NAME ${PATH} NAME)
    set(BINARY_PATH ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}/${NAME})
    set(SOURCE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/${PATH})
    configure_file(${SOURCE_PATH}.mtl ${BINARY_PATH}.mtl COPYONLY)
    configure_file(${SOURCE_PATH}.obj ${BINARY_PATH}.obj COPYONLY)
    configure_file(${SOURCE_PATH}.png ${BINARY_PATH}.png COPYONLY)
    configure_file(${SOURCE_PATH}.vox ${BINARY_PATH}.vox COPYONLY)
endfunction()